# Generated by Django 4.0.4 on 2022-05-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(max_length=150, primary_key=True, serialize=False)),
                ('study_group', models.CharField(max_length=10)),
            ],
        ),
    ]
