# Generated by Django 4.0.4 on 2022-05-18 18:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayPeriod',
            fields=[
                ('period', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90)),
                ('form', models.CharField(blank=True, max_length=10)),
                ('audience_name', models.CharField(blank=True, max_length=10)),
                ('on_weeks', models.CharField(max_length=50, validators=[django.core.validators.int_list_validator])),
                ('test_weeks', models.CharField(max_length=50, validators=[django.core.validators.int_list_validator])),
                ('test', models.CharField(blank=True, max_length=100)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleWeek',
            fields=[
                ('count', models.IntegerField(primary_key=True, serialize=False)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.dayperiod')),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.scheduleday')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.weekday'),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='schedule_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.scheduleweek'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.scheduledayperiod'),
        ),
    ]
