# Generated by Django 4.0.4 on 2022-05-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('study_group', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
