# Generated by Django 4.0.4 on 2022-05-18 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day_app', '0002_scheduledayperiod_schedule_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='period',
        ),
        migrations.RemoveField(
            model_name='scheduledayperiod',
            name='period',
        ),
        migrations.RemoveField(
            model_name='scheduledayperiod',
            name='schedule_day',
        ),
        migrations.RemoveField(
            model_name='scheduleday',
            name='name',
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DayPeriod',
        ),
        migrations.DeleteModel(
            name='ScheduleDayPeriod',
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
        migrations.AddField(
            model_name='schedulelesson',
            name='schedule_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.scheduleday'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day_app.schedulelesson'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
