# Generated by Django 4.0.4 on 2022-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_app', '0003_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='student_id',
        ),
    ]
